### ISSUE TITLE
 dereferencing pointer to incomplete type ‘SSL {aka struct ssl_st}’

### ISSUE THREAD

**Issue by jia0511** [xueqing/exosip#4]
eXtl_dtls.c: In function 'shutdown_free_client_dtls':
eXtl_dtls.c:237:43: error: dereferencing pointer to incomplete type 'SSL {aka struct ssl_st}'
       (reserved->socket_tab[pos].ssl_conn)->rbio = rbio;
                                           ^~
eXtl_dtls.c: In function 'dtls_tl_free':
eXtl_dtls.c:298:3: warning: 'ERR_remove_state' is deprecated [-Wdeprecated-declarations]
   ERR_remove_state (0);
帮我看下这是什么问题？

**Comment by xueqing** [comment]
参考文档说明 <https://github.com/xueqing/exosip/blob/caaf34b2af4a6606ecd5e39f47e1ca5be7b8384b/README.md#6-ubuntu-20-%E7%BC%96%E8%AF%91>
